server:
  port: 8080 # 服务端口
  servlet:
    context-path: /api
spring:
  application:
    name: AI-ChatServer # 应用名称
    version: 1.0.0 # 应用版本
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # 兼容模式
      api-key: sk-*****************************f # API密钥
      chat:
        options:
          model: qwen-max # 对话模型
      embedding:
        options:
          model: text-embedding-v3 # 嵌入模型
          dimensions: 1024 # 嵌入维度
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client
        version: 1.0.0
        type: ASYNC # 或者 SYNC，但不能混用
        request-timeout: 120s
        toolcallback:
          enabled: true
        sse:
          connections:
            WebSearch:
              url: https://dashscope.aliyuncs.com
              sse-endpoint: /api/v1/mcps/WebSearch/sse
            AntV:
              url: https://dashscope.aliyuncs.com
              sse-endpoint: /api/v1/mcps/antv-visualization-chart/sse
            Qtf:
              url: https://dashscope.aliyuncs.com
              sse-endpoint: /api/v1/mcps/qtf_mcp/sse
        streamable-http:
          connections:
            Amap:
              url: https://mcp.amap.com
              endpoint: /mcp?key=*********************
  datasource: # mysql数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lumina?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false
    username: root
    password: 1234
  data: # redis数据源
    redis:
      password: 1234
      host: 192.168.88.88
      port: 6379
      database: 8
      connect-timeout: 5000
    mongodb:
      uri: mongodb://192.168.88.88:27017/lumina
      username: root
      password: 1234
      host: 192.168.88.88
      database: lumina
      port: 27017
  mail: # 邮箱配置
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: 2869***577@qq.com
    password: jgdsdnlbbsnh****
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
logging: # 日志配置
  level:
    org.springframework.ai.mcp: debug # AI对话的日志级别
mybatis-plus: # mybatis-plus配置
  type-aliases-package: com.kk.domain.po # 别名扫描包
  mapper-locations: "classpath*:/mapper/**/*.xml" # Mapper.xml文件地址，默认值
  configuration:
    map-underscore-to-camel-case: true # 否开启下划线和驼峰的映射
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null # 更新策略:只更新非空字段
      logic-delete-field: isDeleted  # 全局逻辑删除字段
      logic-delete-value: 1          # 删除标记值
      logic-not-delete-value: 0      # 未删除标记值
lumina:
  jwt:
    secret-key: f**********n*n
    ttl-days: 3
minio:
  endpoint: http://192.168.88.88:9000
  access-key: root
  secret-key: 12345678
google:
  client-id: 532270517013-649669eme*************************.com
  client-secret: GOCSPX-ByidOlNKF*******7_dxRWYYPTwrj
  user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
